# Generated by Django 4.0.2 on 2022-03-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_attachment_uri_alter_attachment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_admin', to='main.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='members', to='main.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignees',
            unique_together={('issueId', 'userId')},
        ),
    ]
