# Generated by Django 4.0.2 on 2022-04-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='isComplete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueSeverityId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.issueseverity'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.issuetype'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='projectid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
