# Generated by Django 4.0.2 on 2022-04-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_issue_iscomplete_alter_issue_issueseverityid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='time_estimate',
        ),
        migrations.AddField(
            model_name='issuetype',
            name='needSeverity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='projectid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
