# Generated by Django 4.0.2 on 2022-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_issuewithtitles_issueseverity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuewithtitles',
            name='project',
            field=models.JSONField(),
        ),
    ]
