# Generated by Django 4.0.2 on 2022-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_issuewithtitles_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuewithtitles',
            name='user',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
